### ISSUE TITLE
default branch discussion: `dev` vs `master`

### ISSUE THREAD

**Issue by kyungpyoda** [boostcamp-2020/Project17-A-Map#21]
default 브랜치를 `dev`로 할 지 `master`로 할 지 의논하는 이슈입니다.

**Comment by kyungpyoda** [comment]
PR 메시지에 `Close #0` 이런 식으로 이슈와 연결하여 머지될 때 자동으로 닫히도록 할 수 있는데,
default 브랜치로의 머지일 때만 동작함..

두 가지 선택을 할 수 있다고 보는데요..
1. 커밋 메시지에 관련된 이슈를 닫는 `Close #0`을 포함하여 커밋한다.
2. dev를 default 브랜치로 지정한다.

여기서 두 번째 방법이 PR 시 base를 master에서 dev로 바꿔주는 귀찮음도 덜어주기까지 하니 좋다고 생각합니다.

**Comment by yskpth91** [comment]
넵 저는 개발기간동안은 디폴트 브랜치 dev로 바꾸는거 찬성입니다~

**Comment by kyungpyoda** [comment]
dev로 바꾸기로 땅땅땅!
