### ISSUE TITLE
K Means 클러스터링 이후 데이터 중복

### ISSUE THREAD

**Issue by kyungpyoda** [boostcamp-2020/Project17-A-Map#36]
- 추가, 제거 로직 문제인듯..

**Comment by hoonv** [comment]
어떻게 진행중이신가요 ?

**Comment by kyungpyoda** [comment]
수정은 하였으나 당장 다른 클러스터링 알고리즘들이 잘 돌아가기도 하고 다른 기능 구현에 박차를 가해야하기 때문에.. 추후에 다시 정리해서 PR올리겠습니다.

**Comment by kyungpyoda** [comment]
K Means Elbow Method 사용은 접게되어서 close..
