### ISSUE TITLE
PullUpView의 2% 부족한 Interaction..

### ISSUE THREAD

**Issue by kyungpyoda** [boostcamp-2020/Project17-A-Map#41]
- CollectionView의 Scroll과 PullUpView를 움직이는 PanGesture 사이의 자연스러운 전환이 부족..
- Scroll을 위로 올리다가(제스쳐 방향은 아래) Scroll이 Top에 위치하면 PullUpView를 아래로 당기는 것은 잘 되지만, PullUpView의 PanGesture로 넘어가고 나서 **다시 PullUpView가 FullViewPosition에 도달하면 Scroll에 제스쳐가 넘어가도록 해야하는데 안됨...**

<img height="400" src="https://user-images.githubusercontent.com/44656036/100988565-37595c80-3593-11eb-9adc-2e2a5dcfaa9a.gif"><img height="400" src="https://user-images.githubusercontent.com/44656036/100988621-42ac8800-3593-11eb-8632-0f1c29348dd9.gif">

흑흑 ㅜㅜ
![image](https://user-images.githubusercontent.com/44656036/100983428-a67f8280-358c-11eb-8ec5-66b5418fa511.png)

**Comment by hoonv** [comment]
swipe gesture 사용해보셨나요 ?

**Comment by kyungpyoda** [comment]
음 swipe gesture는 관련이 없는 것 같아요
지금 문제는 gesture가 CollectionView의 Scroll에 먹히다가 PullUpView에 먹히다가 왔다갔다 자연스럽게 전환이 안되어서 문제입니닷 ㅜㅜ
