### ISSUE TITLE
Kmeans 알고리즘 성능 개선 (너무 느림)

### ISSUE THREAD

**Issue by hoonv** [boostcamp-2020/Project17-A-Map#47]

**Comment by kyungpyoda** [comment]
#50 엄청 많이 개선됐네요! 화이팅입니다🔥

**Comment by hoonv** [comment]
K값을 Place의 갯수에 맞게 끔 조정해서 어느정도의 속도를 보장하게 변경하였고 적절한 K값을 찾기위해 여러개의 K로 클러스터링해보는데 이부분을 병렬처리로 진행해서 성능을 조금 개선했습니다.
